blank_issues_enabled: false
contact_links:
  - name: Report in private
    url: https://github.com/hollerbell/holler-bell/security/policy
    about: For security problems and anything else you'd rather not post in public.
